name: volo_meeting
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  based_avatar: ^1.0.3
  based_list: ^1.1.1
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.4.3
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  mobile_scanner: ^3.4.1 # TIPS: Only for Android and iOS
  nanoid: ^1.0.0
  riverpod_annotation: ^2.2.0
  shared_preferences: ^2.2.1
  sticky_and_expandable_list: ^1.1.3
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true
